###########
# site.title

title:    'minecraft-alaina'
subtitle: 'CS 175: Project in AI (in Minecraft)'

baseurl: "/minecraft-alaina"
url: "https://bdon1990x.github.io"

#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md

theme: jekyll-theme-cayman
